spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content-center
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      #  cluster-name: NANJING
  application:
    name: content-center
server:
  port: 11081
##通过配置文件的方式配置ribbon的规则
#user-center:
#  ribbon:
ribbon:
  eager-load:
    clients: user-center
    enabled: true
logging:
  level:
    com.feather.contentcenter.feignClient.UserFeignClient : debug
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule